#ifndef VMScriptGuideStrings_h
#define VMScriptGuideStrings_h

#include <map>
#include <string>

static std::map<std::string, std::map<std::string, std::string>> kScriptGuideStrings = {
    
    {"tips_content", {
        {"en", "💡 <b>Tips:</b> Type suffixes use standard naming: signed integers (I8, I16, I32, I64), unsigned integers (U8, U16, U32, U64), floats (F32, F64). Types are case-insensitive. This document covers all VM available commands. Also compatible with h5gg syntax."},
        {"zh", "💡 <b>核心提示：</b> 类型后缀采用标准化命名：有符号整数 (I8, I16, I32, I64)、无符号整数 (U8, U16, U32, U64)、浮点数 (F32, F64)。类型不区分大小写。本文档涵盖VM所有可用指令，同时兼容 h5gg 语法。"},
        {"ja", "💡 <b>ヒント：</b> 型サフィックスは標準命名を使用：符号付き整数 (I8, I16, I32, I64)、符号なし整数 (U8, U16, U32, U64)、浮動小数点 (F32, F64)。型は大文字小文字を区別しません。このドキュメントはVMの全コマンドをカバーし、h5gg構文とも互換性があります。"},
        {"ko", "💡 <b>팁:</b> 타입 접미사는 표준 명명 사용: 부호 있는 정수 (I8, I16, I32, I64), 부호 없는 정수 (U8, U16, U32, U64), 부동소수점 (F32, F64). 타입은 대소문자를 구분하지 않습니다. 이 문서는 모든 VM 명령을 다루며 h5gg 구문과도 호환됩니다."},
        {"ru", "💡 <b>Советы:</b> Суффиксы типов используют стандартные имена: знаковые целые (I8, I16, I32, I64), беззнаковые целые (U8, U16, U32, U64), числа с плавающей точкой (F32, F64). Типы не чувствительны к регистру. Этот документ охватывает все команды VM и совместим с синтаксисом h5gg."},
        {"es", "💡 <b>Consejos:</b> Los sufijos de tipo usan nombres estándar: enteros con signo (I8, I16, I32, I64), enteros sin signo (U8, U16, U32, U64), flotantes (F32, F64). Los tipos no distinguen mayúsculas. Este documento cubre todos los comandos VM y es compatible con la sintaxis h5gg."},
        {"vi", "💡 <b>Mẹo:</b> Hậu tố kiểu sử dụng tên chuẩn: số nguyên có dấu (I8, I16, I32, I64), số nguyên không dấu (U8, U16, U32, U64), số thực (F32, F64). Kiểu không phân biệt chữ hoa/thường. Tài liệu này bao gồm tất cả lệnh VM và tương thích với cú pháp h5gg."},
        {"pt", "💡 <b>Dicas:</b> Sufixos de tipo usam nomes padrão: inteiros com sinal (I8, I16, I32, I64), inteiros sem sinal (U8, U16, U32, U64), flutuantes (F32, F64). Tipos não diferenciam maiúsculas. Este documento cobre todos os comandos VM e é compatível com sintaxe h5gg."},
        {"fr", "💡 <b>Conseils:</b> Les suffixes de type utilisent des noms standard: entiers signés (I8, I16, I32, I64), entiers non signés (U8, U16, U32, U64), flottants (F32, F64). Les types ne sont pas sensibles à la casse. Ce document couvre toutes les commandes VM et est compatible avec la syntaxe h5gg."},
        {"de", "💡 <b>Tipps:</b> Typ-Suffixe verwenden Standardnamen: vorzeichenbehaftete Ganzzahlen (I8, I16, I32, I64), vorzeichenlose Ganzzahlen (U8, U16, U32, U64), Gleitkommazahlen (F32, F64). Typen sind nicht case-sensitiv. Dieses Dokument deckt alle VM-Befehle ab und ist mit h5gg-Syntax kompatibel."},
        {"th", "💡 <b>เคล็ดลับ:</b> คำต่อท้ายประเภทใช้ชื่อมาตรฐาน: จำนวนเต็มมีเครื่องหมาย (I8, I16, I32, I64), จำนวนเต็มไม่มีเครื่องหมาย (U8, U16, U32, U64), ทศนิยม (F32, F64) ประเภทไม่แยกตัวพิมพ์ใหญ่/เล็ก เอกสารนี้ครอบคลุมคำสั่ง VM ทั้งหมดและเข้ากันได้กับไวยากรณ์ h5gg"},
        {"ar", "💡 <b>نصائح:</b> لواحق الأنواع تستخدم تسمية قياسية: أعداد صحيحة موقعة (I8, I16, I32, I64)، أعداد صحيحة غير موقعة (U8, U16, U32, U64)، أعداد عشرية (F32, F64). الأنواع لا تفرق بين الأحرف الكبيرة والصغيرة. يغطي هذا المستند جميع أوامر VM ومتوافق مع صيغة h5gg."},
    }},

    {"section_1", {
        {"en", "1. Exact Search"},
        {"zh", "1. 精确搜索 (Search)"},
        {"ja", "1. 正確検索 (Search)"},
        {"ko", "1. 정확한 검색 (Search)"},
        {"ru", "1. Точный поиск (Search)"},
        {"es", "1. Búsqueda Exacta"},
        {"vi", "1. Tìm Kiếm Chính Xác"},
        {"pt", "1. Busca Exata"},
        {"fr", "1. Recherche Exacte"},
        {"de", "1. Exakte Suche"},
        {"th", "1. ค้นหาแม่นยำ"},
        {"ar", "1. البحث الدقيق"},
    }},
    {"section_2", {
        {"en", "2. Refine Search"},
        {"zh", "2. 再次搜索 (Refine)"},
        {"ja", "2. 絞り込み検索 (Refine)"},
        {"ko", "2. 검색 정제 (Refine)"},
        {"ru", "2. Уточнить поиск (Refine)"},
        {"es", "2. Refinar Búsqueda"},
        {"vi", "2. Lọc Tìm Kiếm"},
        {"pt", "2. Refinar Busca"},
        {"fr", "2. Affiner la Recherche"},
        {"de", "2. Suche Verfeinern"},
        {"th", "2. กรองการค้นหา"},
        {"ar", "2. تحسين البحث"},
    }},
    {"section_3", {
        {"en", "3. Fuzzy Search"},
        {"zh", "3. 模糊搜索 (Fuzzy)"},
        {"ja", "3. ファジー検索 (Fuzzy)"},
        {"ko", "3. 퍼지 검색 (Fuzzy)"},
        {"ru", "3. Нечёткий поиск (Fuzzy)"},
        {"es", "3. Búsqueda Difusa"},
        {"vi", "3. Tìm Kiếm Mờ"},
        {"pt", "3. Busca Difusa"},
        {"fr", "3. Recherche Floue"},
        {"de", "3. Unscharfe Suche"},
        {"th", "3. ค้นหาคลุมเครือ"},
        {"ar", "3. البحث الضبابي"},
    }},
    {"section_4", {
        {"en", "4. Group Search"},
        {"zh", "4. 联合搜索 (Group)"},
        {"ja", "4. グループ検索 (Group)"},
        {"ko", "4. 그룹 검색 (Group)"},
        {"ru", "4. Групповой поиск (Group)"},
        {"es", "4. Búsqueda de Grupo"},
        {"vi", "4. Tìm Kiếm Nhóm"},
        {"pt", "4. Busca em Grupo"},
        {"fr", "4. Recherche de Groupe"},
        {"de", "4. Gruppensuche"},
        {"th", "4. ค้นหากลุ่ม"},
        {"ar", "4. البحث الجماعي"},
    }},
    {"section_5", {
        {"en", "5. Nearby Search"},
        {"zh", "5. 临近搜索 (Nearby)"},
        {"ja", "5. 近傍検索 (Nearby)"},
        {"ko", "5. 근처 검색 (Nearby)"},
        {"ru", "5. Поиск рядом (Nearby)"},
        {"es", "5. Búsqueda Cercana"},
        {"vi", "5. Tìm Kiếm Lân Cận"},
        {"pt", "5. Busca Próxima"},
        {"fr", "5. Recherche à Proximité"},
        {"de", "5. Umgebungssuche"},
        {"th", "5. ค้นหาใกล้เคียง"},
        {"ar", "5. البحث القريب"},
    }},
    {"section_6", {
        {"en", "6. Signature Search"},
        {"zh", "6. 特征码搜索 (Signature)"},
        {"ja", "6. シグネチャ検索 (Signature)"},
        {"ko", "6. 시그니처 검색 (Signature)"},
        {"ru", "6. Поиск по сигнатуре (Signature)"},
        {"es", "6. Búsqueda de Firma"},
        {"vi", "6. Tìm Kiếm Chữ Ký"},
        {"pt", "6. Busca por Assinatura"},
        {"fr", "6. Recherche de Signature"},
        {"de", "6. Signatursuche"},
        {"th", "6. ค้นหาลายเซ็น"},
        {"ar", "6. البحث بالتوقيع"},
    }},
    {"section_7", {
        {"en", "7. Results Operations"},
        {"zh", "7. 结果操作 (Results)"},
        {"ja", "7. 結果操作 (Results)"},
        {"ko", "7. 결과 작업 (Results)"},
        {"ru", "7. Операции с результатами (Results)"},
        {"es", "7. Operaciones de Resultados"},
        {"vi", "7. Thao Tác Kết Quả"},
        {"pt", "7. Operações de Resultados"},
        {"fr", "7. Opérations sur les Résultats"},
        {"de", "7. Ergebnisoperationen"},
        {"th", "7. การดำเนินการผลลัพธ์"},
        {"ar", "7. عمليات النتائج"},
    }},
    {"section_8", {
        {"en", "8. Memory I/O"},
        {"zh", "8. 地址读写 (Memory I/O)"},
        {"ja", "8. メモリI/O"},
        {"ko", "8. 메모리 I/O"},
        {"ru", "8. Память I/O"},
        {"es", "8. E/S de Memoria"},
        {"vi", "8. Đọc/Ghi Bộ Nhớ"},
        {"pt", "8. E/S de Memória"},
        {"fr", "8. E/S Mémoire"},
        {"de", "8. Speicher I/O"},
        {"th", "8. อ่าน/เขียนหน่วยความจำ"},
        {"ar", "8. قراءة/كتابة الذاكرة"},
    }},
    {"section_9", {
        {"en", "9. Module Info"},
        {"zh", "9. 模块信息 (Module Info)"},
        {"ja", "9. モジュール情報"},
        {"ko", "9. 모듈 정보"},
        {"ru", "9. Информация о модулях"},
        {"es", "9. Info de Módulos"},
        {"vi", "9. Thông Tin Module"},
        {"pt", "9. Info de Módulos"},
        {"fr", "9. Info des Modules"},
        {"de", "9. Modul-Info"},
        {"th", "9. ข้อมูลโมดูล"},
        {"ar", "9. معلومات الوحدة"},
    }},
    {"section_10", {
        {"en", "10. System Functions"},
        {"zh", "10. 系统功能 (System)"},
        {"ja", "10. システム機能"},
        {"ko", "10. 시스템 기능"},
        {"ru", "10. Системные функции"},
        {"es", "10. Funciones del Sistema"},
        {"vi", "10. Chức Năng Hệ Thống"},
        {"pt", "10. Funções do Sistema"},
        {"fr", "10. Fonctions Système"},
        {"de", "10. Systemfunktionen"},
        {"th", "10. ฟังก์ชันระบบ"},
        {"ar", "10. وظائف النظام"},
    }},
    {"section_11", {
        {"en", "11. Value Lock"},
        {"zh", "11. 数值锁定 (Lock)"},
        {"ja", "11. 値ロック (Lock)"},
        {"ko", "11. 값 잠금 (Lock)"},
        {"ru", "11. Блокировка значений (Lock)"},
        {"es", "11. Bloqueo de Valores"},
        {"vi", "11. Khóa Giá Trị"},
        {"pt", "11. Bloqueio de Valores"},
        {"fr", "11. Verrouillage de Valeurs"},
        {"de", "11. Wertsperre"},
        {"th", "11. ล็อกค่า"},
        {"ar", "11. قفل القيمة"},
    }},
    {"section_demo", {
        {"en", "Complete Example"},
        {"zh", "完整示例"},
        {"ja", "完全な例"},
        {"ko", "전체 예제"},
        {"ru", "Полный пример"},
        {"es", "Ejemplo Completo"},
        {"vi", "Ví Dụ Hoàn Chỉnh"},
        {"pt", "Exemplo Completo"},
        {"fr", "Exemple Complet"},
        {"de", "Vollständiges Beispiel"},
        {"th", "ตัวอย่างสมบูรณ์"},
        {"ar", "مثال كامل"},
    }},

    {"btn_copy", {
        {"en", "Copy"},
        {"zh", "复制"},
        {"ja", "コピー"},
        {"ko", "복사"},
        {"ru", "Копировать"},
        {"es", "Copiar"},
        {"vi", "Sao Chép"},
        {"pt", "Copiar"},
        {"fr", "Copier"},
        {"de", "Kopieren"},
        {"th", "คัดลอก"},
        {"ar", "نسخ"},
    }},
    {"btn_insert", {
        {"en", "Insert"},
        {"zh", "插入"},
        {"ja", "挿入"},
        {"ko", "삽입"},
        {"ru", "Вставить"},
        {"es", "Insertar"},
        {"vi", "Chèn"},
        {"pt", "Inserir"},
        {"fr", "Insérer"},
        {"de", "Einfügen"},
        {"th", "แทรก"},
        {"ar", "إدراج"},
    }},

    {"th_param", {
        {"en", "Param"},
        {"zh", "参数"},
        {"ja", "パラメータ"},
        {"ko", "매개변수"},
        {"ru", "Параметр"},
        {"es", "Parámetro"},
        {"vi", "Tham Số"},
        {"pt", "Parâmetro"},
        {"fr", "Paramètre"},
        {"de", "Parameter"},
        {"th", "พารามิเตอร์"},
        {"ar", "المعامل"},
    }},
    {"th_desc", {
        {"en", "Description"},
        {"zh", "说明"},
        {"ja", "説明"},
        {"ko", "설명"},
        {"ru", "Описание"},
        {"es", "Descripción"},
        {"vi", "Mô Tả"},
        {"pt", "Descrição"},
        {"fr", "Description"},
        {"de", "Beschreibung"},
        {"th", "คำอธิบาย"},
        {"ar", "الوصف"},
    }},

    {"card_results_title", {
        {"en", "Get & Modify Results"},
        {"zh", "结果获取与修改"},
        {"ja", "結果の取得と変更"},
        {"ko", "결과 가져오기 및 수정"},
        {"ru", "Получение и изменение результатов"},
        {"es", "Obtener y Modificar Resultados"},
        {"vi", "Lấy và Sửa Kết Quả"},
        {"pt", "Obter e Modificar Resultados"},
        {"fr", "Obtenir et Modifier les Résultats"},
        {"de", "Ergebnisse Abrufen und Ändern"},
        {"th", "รับและแก้ไขผลลัพธ์"},
        {"ar", "الحصول على النتائج وتعديلها"},
    }},
    {"card_io_title", {
        {"en", "Direct Address Operations"},
        {"zh", "直接地址操作"},
        {"ja", "直接アドレス操作"},
        {"ko", "직접 주소 작업"},
        {"ru", "Прямые операции с адресами"},
        {"es", "Operaciones Directas de Dirección"},
        {"vi", "Thao Tác Địa Chỉ Trực Tiếp"},
        {"pt", "Operações Diretas de Endereço"},
        {"fr", "Opérations d'Adresse Directes"},
        {"de", "Direkte Adressoperationen"},
        {"th", "การดำเนินการที่อยู่โดยตรง"},
        {"ar", "عمليات العنوان المباشرة"},
    }},
    {"card_module_title", {
        {"en", "Process Modules"},
        {"zh", "进程模块"},
        {"ja", "プロセスモジュール"},
        {"ko", "프로세스 모듈"},
        {"ru", "Модули процесса"},
        {"es", "Módulos del Proceso"},
        {"vi", "Module Tiến Trình"},
        {"pt", "Módulos do Processo"},
        {"fr", "Modules du Processus"},
        {"de", "Prozessmodule"},
        {"th", "โมดูลกระบวนการ"},
        {"ar", "وحدات العملية"},
    }},
    {"card_sys_title", {
        {"en", "Utilities"},
        {"zh", "辅助功能"},
        {"ja", "ユーティリティ"},
        {"ko", "유틸리티"},
        {"ru", "Утилиты"},
        {"es", "Utilidades"},
        {"vi", "Tiện Ích"},
        {"pt", "Utilitários"},
        {"fr", "Utilitaires"},
        {"de", "Hilfsfunktionen"},
        {"th", "ยูทิลิตี้"},
        {"ar", "الأدوات المساعدة"},
    }},
    {"card_lock_title", {
        {"en", "Lock & Unlock"},
        {"zh", "锁定与解锁"},
        {"ja", "ロックとアンロック"},
        {"ko", "잠금 및 해제"},
        {"ru", "Блокировка и разблокировка"},
        {"es", "Bloquear y Desbloquear"},
        {"vi", "Khóa và Mở Khóa"},
        {"pt", "Bloquear e Desbloquear"},
        {"fr", "Verrouiller et Déverrouiller"},
        {"de", "Sperren und Entsperren"},
        {"th", "ล็อกและปลดล็อก"},
        {"ar", "القفل وإلغاء القفل"},
    }},
    {"card_demo_title", {
        {"en", "Single-Player Process Debug Example"},
        {"zh", "单机进程调试示例"},
        {"ja", "シングルプレイヤープロセスデバッグ例"},
        {"ko", "싱글 플레이어 프로세스 디버그 예제"},
        {"ru", "Пример отладки одиночного процесса"},
        {"es", "Ejemplo de Depuración de Proceso"},
        {"vi", "Ví Dụ Debug Tiến Trình Đơn"},
        {"pt", "Exemplo de Debug de Processo"},
        {"fr", "Exemple de Débogage de Processus"},
        {"de", "Einzelprozess-Debug-Beispiel"},
        {"th", "ตัวอย่างการดีบักกระบวนการ"},
        {"ar", "مثال تصحيح العملية"},
    }},

    {"desc_search", {
        {"en", "Search for exact values within specified range, supports custom start/end addresses."},
        {"zh", "在指定范围内搜索精确数值，支持自定义起止地址。"},
        {"ja", "指定範囲内で正確な値を検索、カスタム開始/終了アドレスをサポート。"},
        {"ko", "지정된 범위 내에서 정확한 값을 검색하고 사용자 정의 시작/끝 주소를 지원합니다."},
        {"ru", "Поиск точных значений в указанном диапазоне, поддержка пользовательских адресов начала/конца."},
        {"es", "Buscar valores exactos dentro del rango especificado, soporta direcciones de inicio/fin personalizadas."},
        {"vi", "Tìm kiếm giá trị chính xác trong phạm vi chỉ định, hỗ trợ địa chỉ bắt đầu/kết thúc tùy chỉnh."},
        {"pt", "Buscar valores exatos dentro do intervalo especificado, suporta endereços de início/fim personalizados."},
        {"fr", "Rechercher des valeurs exactes dans la plage spécifiée, prend en charge les adresses de début/fin personnalisées."},
        {"de", "Suche nach exakten Werten im angegebenen Bereich, unterstützt benutzerdefinierte Start-/Endadressen."},
        {"th", "ค้นหาค่าที่แม่นยำภายในช่วงที่กำหนด รองรับที่อยู่เริ่มต้น/สิ้นสุดที่กำหนดเอง"},
        {"ar", "البحث عن قيم دقيقة ضمن النطاق المحدد، يدعم عناوين البداية/النهاية المخصصة."},
    }},
    {"desc_refine", {
        {"en", "Filter existing results with various comparison modes."},
        {"zh", "在已有结果中进一步筛选，支持多种比对模式。"},
        {"ja", "既存の結果を様々な比較モードでフィルタリング。"},
        {"ko", "다양한 비교 모드로 기존 결과를 필터링합니다."},
        {"ru", "Фильтрация существующих результатов с различными режимами сравнения."},
        {"es", "Filtrar resultados existentes con varios modos de comparación."},
        {"vi", "Lọc kết quả hiện có với các chế độ so sánh khác nhau."},
        {"pt", "Filtrar resultados existentes com vários modos de comparação."},
        {"fr", "Filtrer les résultats existants avec différents modes de comparaison."},
        {"de", "Vorhandene Ergebnisse mit verschiedenen Vergleichsmodi filtern."},
        {"th", "กรองผลลัพธ์ที่มีอยู่ด้วยโหมดเปรียบเทียบต่างๆ"},
        {"ar", "تصفية النتائج الموجودة بأوضاع مقارنة مختلفة."},
    }},
    {"desc_fuzzy", {
        {"en", "Initialize fuzzy search by taking memory snapshot, then use refine to filter changes."},
        {"zh", "初始化模糊搜索，记录当前内存快照，后续使用 refine 筛选变化。"},
        {"ja", "メモリスナップショットを取得してファジー検索を初期化、その後refineで変更をフィルタリング。"},
        {"ko", "메모리 스냅샷을 찍어 퍼지 검색을 초기화한 다음 refine을 사용하여 변경 사항을 필터링합니다."},
        {"ru", "Инициализация нечёткого поиска путём создания снимка памяти, затем использование refine для фильтрации изменений."},
        {"es", "Inicializar búsqueda difusa tomando instantánea de memoria, luego usar refine para filtrar cambios."},
        {"vi", "Khởi tạo tìm kiếm mờ bằng cách chụp ảnh bộ nhớ, sau đó sử dụng refine để lọc thay đổi."},
        {"pt", "Inicializar busca difusa tirando snapshot da memória, depois usar refine para filtrar mudanças."},
        {"fr", "Initialiser la recherche floue en prenant un instantané mémoire, puis utiliser refine pour filtrer les changements."},
        {"de", "Unscharfe Suche durch Speicher-Snapshot initialisieren, dann refine verwenden um Änderungen zu filtern."},
        {"th", "เริ่มต้นการค้นหาคลุมเครือโดยถ่ายภาพหน่วยความจำ จากนั้นใช้ refine เพื่อกรองการเปลี่ยนแปลง"},
        {"ar", "تهيئة البحث الضبابي بأخذ لقطة للذاكرة، ثم استخدام refine لتصفية التغييرات."},
    }},
    {"desc_group", {
        {"en", "Search multiple related values simultaneously, supports mixed types and offset ranges."},
        {"zh", "同时搜索多个关联数值，支持混合类型和偏移范围。"},
        {"ja", "複数の関連値を同時に検索、混合型とオフセット範囲をサポート。"},
        {"ko", "여러 관련 값을 동시에 검색하고 혼합 유형과 오프셋 범위를 지원합니다."},
        {"ru", "Одновременный поиск нескольких связанных значений, поддержка смешанных типов и диапазонов смещения."},
        {"es", "Buscar múltiples valores relacionados simultáneamente, soporta tipos mixtos y rangos de offset."},
        {"vi", "Tìm kiếm nhiều giá trị liên quan đồng thời, hỗ trợ kiểu hỗn hợp và phạm vi offset."},
        {"pt", "Buscar múltiplos valores relacionados simultaneamente, suporta tipos mistos e intervalos de offset."},
        {"fr", "Rechercher plusieurs valeurs liées simultanément, prend en charge les types mixtes et les plages d'offset."},
        {"de", "Mehrere verwandte Werte gleichzeitig suchen, unterstützt gemischte Typen und Offset-Bereiche."},
        {"th", "ค้นหาค่าที่เกี่ยวข้องหลายค่าพร้อมกัน รองรับประเภทผสมและช่วง offset"},
        {"ar", "البحث عن قيم متعددة مرتبطة في وقت واحد، يدعم الأنواع المختلطة ونطاقات الإزاحة."},
    }},
    {"desc_nearby", {
        {"en", "Search for other values near current results, useful for locating related data in structures."},
        {"zh", "在当前结果附近搜索其他数值，用于定位结构体内的关联数据。"},
        {"ja", "現在の結果の近くで他の値を検索、構造体内の関連データの特定に便利。"},
        {"ko", "현재 결과 근처에서 다른 값을 검색하여 구조체 내 관련 데이터를 찾는 데 유용합니다."},
        {"ru", "Поиск других значений рядом с текущими результатами, полезно для поиска связанных данных в структурах."},
        {"es", "Buscar otros valores cerca de los resultados actuales, útil para localizar datos relacionados en estructuras."},
        {"vi", "Tìm kiếm các giá trị khác gần kết quả hiện tại, hữu ích để định vị dữ liệu liên quan trong cấu trúc."},
        {"pt", "Buscar outros valores perto dos resultados atuais, útil para localizar dados relacionados em estruturas."},
        {"fr", "Rechercher d'autres valeurs près des résultats actuels, utile pour localiser des données liées dans les structures."},
        {"de", "Nach anderen Werten in der Nähe aktueller Ergebnisse suchen, nützlich zum Auffinden verwandter Daten in Strukturen."},
        {"th", "ค้นหาค่าอื่นใกล้ผลลัพธ์ปัจจุบัน มีประโยชน์สำหรับการค้นหาข้อมูลที่เกี่ยวข้องในโครงสร้าง"},
        {"ar", "البحث عن قيم أخرى بالقرب من النتائج الحالية، مفيد لتحديد البيانات المرتبطة في الهياكل."},
    }},
    {"desc_signature", {
        {"en", "Locate memory addresses using hex patterns, supports ?? wildcard."},
        {"zh", "使用十六进制特征码定位内存地址，支持 ?? 通配符。"},
        {"ja", "16進パターンを使用してメモリアドレスを特定、??ワイルドカードをサポート。"},
        {"ko", "16진수 패턴을 사용하여 메모리 주소를 찾고 ?? 와일드카드를 지원합니다."},
        {"ru", "Поиск адресов памяти по hex-паттернам, поддержка ?? в качестве подстановочного знака."},
        {"es", "Localizar direcciones de memoria usando patrones hex, soporta comodín ??."},
        {"vi", "Định vị địa chỉ bộ nhớ bằng mẫu hex, hỗ trợ ký tự đại diện ??."},
        {"pt", "Localizar endereços de memória usando padrões hex, suporta curinga ??."},
        {"fr", "Localiser les adresses mémoire en utilisant des motifs hex, prend en charge le joker ??."},
        {"de", "Speicheradressen mit Hex-Mustern lokalisieren, unterstützt ?? Platzhalter."},
        {"th", "ค้นหาที่อยู่หน่วยความจำโดยใช้รูปแบบ hex รองรับ ?? wildcard"},
        {"ar", "تحديد عناوين الذاكرة باستخدام أنماط hex، يدعم ?? كحرف بدل."},
    }},
    {"desc_results", {
        {"en", "Get result count, result list, and batch modify."},
        {"zh", "获取搜索结果数量、结果列表，以及批量修改。"},
        {"ja", "結果数、結果リストの取得、および一括変更。"},
        {"ko", "결과 수, 결과 목록 가져오기 및 일괄 수정."},
        {"ru", "Получение количества результатов, списка результатов и пакетное изменение."},
        {"es", "Obtener cantidad de resultados, lista de resultados y modificación por lotes."},
        {"vi", "Lấy số lượng kết quả, danh sách kết quả và sửa đổi hàng loạt."},
        {"pt", "Obter contagem de resultados, lista de resultados e modificação em lote."},
        {"fr", "Obtenir le nombre de résultats, la liste des résultats et la modification par lots."},
        {"de", "Ergebnisanzahl, Ergebnisliste abrufen und Stapelmodifikation."},
        {"th", "รับจำนวนผลลัพธ์ รายการผลลัพธ์ และแก้ไขเป็นชุด"},
        {"ar", "الحصول على عدد النتائج وقائمة النتائج والتعديل الدفعي."},
    }},
    {"desc_io", {
        {"en", "Perform precise read/write operations on specific memory addresses."},
        {"zh", "对指定内存地址进行精确的读取和写入操作。"},
        {"ja", "特定のメモリアドレスに対して正確な読み書き操作を実行。"},
        {"ko", "특정 메모리 주소에서 정확한 읽기/쓰기 작업을 수행합니다."},
        {"ru", "Выполнение точных операций чтения/записи по конкретным адресам памяти."},
        {"es", "Realizar operaciones precisas de lectura/escritura en direcciones de memoria específicas."},
        {"vi", "Thực hiện các thao tác đọc/ghi chính xác trên các địa chỉ bộ nhớ cụ thể."},
        {"pt", "Realizar operações precisas de leitura/escrita em endereços de memória específicos."},
        {"fr", "Effectuer des opérations de lecture/écriture précises sur des adresses mémoire spécifiques."},
        {"de", "Präzise Lese-/Schreiboperationen an bestimmten Speicheradressen durchführen."},
        {"th", "ดำเนินการอ่าน/เขียนที่แม่นยำบนที่อยู่หน่วยความจำเฉพาะ"},
        {"ar", "إجراء عمليات قراءة/كتابة دقيقة على عناوين ذاكرة محددة."},
    }},
    {"desc_module", {
        {"en", "Get all loaded modules and base addresses, set main module base."},
        {"zh", "获取当前进程的所有加载模块及基准地址，设置主模块基址。"},
        {"ja", "すべてのロードされたモジュールとベースアドレスを取得、メインモジュールベースを設定。"},
        {"ko", "모든 로드된 모듈과 기본 주소를 가져오고 메인 모듈 기본을 설정합니다."},
        {"ru", "Получение всех загруженных модулей и базовых адресов, установка базы главного модуля."},
        {"es", "Obtener todos los módulos cargados y direcciones base, establecer base del módulo principal."},
        {"vi", "Lấy tất cả các module đã tải và địa chỉ cơ sở, đặt cơ sở module chính."},
        {"pt", "Obter todos os módulos carregados e endereços base, definir base do módulo principal."},
        {"fr", "Obtenir tous les modules chargés et adresses de base, définir la base du module principal."},
        {"de", "Alle geladenen Module und Basisadressen abrufen, Hauptmodulbasis setzen."},
        {"th", "รับโมดูลที่โหลดทั้งหมดและที่อยู่ฐาน ตั้งค่าฐานโมดูลหลัก"},
        {"ar", "الحصول على جميع الوحدات المحملة والعناوين الأساسية، تعيين قاعدة الوحدة الرئيسية."},
    }},
    {"desc_system", {
        {"en", "Sleep, logging, toast notifications, float tolerance and other system functions."},
        {"zh", "延时、日志、提示、浮点容差等系统级功能。"},
        {"ja", "スリープ、ログ、トースト通知、浮動小数点許容差などのシステム機能。"},
        {"ko", "슬립, 로깅, 토스트 알림, 부동소수점 허용 오차 및 기타 시스템 기능."},
        {"ru", "Задержка, логирование, всплывающие уведомления, допуск для чисел с плавающей точкой и другие системные функции."},
        {"es", "Suspensión, registro, notificaciones toast, tolerancia de flotantes y otras funciones del sistema."},
        {"vi", "Ngủ, ghi log, thông báo toast, dung sai số thực và các chức năng hệ thống khác."},
        {"pt", "Suspensão, registro, notificações toast, tolerância de float e outras funções do sistema."},
        {"fr", "Pause, journalisation, notifications toast, tolérance des flottants et autres fonctions système."},
        {"de", "Schlaf, Protokollierung, Toast-Benachrichtigungen, Float-Toleranz und andere Systemfunktionen."},
        {"th", "หยุดชั่วคราว บันทึก การแจ้งเตือน toast ความคลาดเคลื่อนทศนิยม และฟังก์ชันระบบอื่นๆ"},
        {"ar", "السكون، التسجيل، إشعارات التوست، تسامح الأعداد العشرية ووظائف النظام الأخرى."},
    }},
    {"desc_lock", {
        {"en", "Lock search results by index or filter condition."},
        {"zh", "锁定搜索结果中的数值，支持按索引或过滤条件筛选。"},
        {"ja", "インデックスまたはフィルター条件で検索結果をロック。"},
        {"ko", "인덱스 또는 필터 조건으로 검색 결과를 잠급니다."},
        {"ru", "Блокировка результатов поиска по индексу или условию фильтра."},
        {"es", "Bloquear resultados de búsqueda por índice o condición de filtro."},
        {"vi", "Khóa kết quả tìm kiếm theo chỉ mục hoặc điều kiện lọc."},
        {"pt", "Bloquear resultados de busca por índice ou condição de filtro."},
        {"fr", "Verrouiller les résultats de recherche par index ou condition de filtre."},
        {"de", "Suchergebnisse nach Index oder Filterbedingung sperren."},
        {"th", "ล็อกผลการค้นหาตามดัชนีหรือเงื่อนไขการกรอง"},
        {"ar", "قفل نتائج البحث حسب الفهرس أو شرط التصفية."},
    }},
    {"desc_demo", {
        {"en", "A complete memory debugging script example showing common workflow."},
        {"zh", "一个完整的内存调试脚本示例，展示常用工作流程。"},
        {"ja", "一般的なワークフローを示す完全なメモリデバッグスクリプト例。"},
        {"ko", "일반적인 워크플로우를 보여주는 완전한 메모리 디버깅 스크립트 예제."},
        {"ru", "Полный пример скрипта отладки памяти, показывающий типичный рабочий процесс."},
        {"es", "Un ejemplo completo de script de depuración de memoria mostrando el flujo de trabajo común."},
        {"vi", "Một ví dụ script debug bộ nhớ hoàn chỉnh hiển thị quy trình làm việc phổ biến."},
        {"pt", "Um exemplo completo de script de debug de memória mostrando o fluxo de trabalho comum."},
        {"fr", "Un exemple complet de script de débogage mémoire montrant le flux de travail courant."},
        {"de", "Ein vollständiges Speicher-Debug-Skript-Beispiel, das den üblichen Arbeitsablauf zeigt."},
        {"th", "ตัวอย่างสคริปต์ดีบักหน่วยความจำที่สมบูรณ์แสดงเวิร์กโฟลว์ทั่วไป"},
        {"ar", "مثال كامل لسكريبت تصحيح الذاكرة يوضح سير العمل الشائع."},
    }},

    {"param_value", {
        {"en", "Value to search (string)"},
        {"zh", "要搜索的数值 (字符串)"},
        {"ja", "検索する値 (文字列)"},
        {"ko", "검색할 값 (문자열)"},
        {"ru", "Значение для поиска (строка)"},
        {"es", "Valor a buscar (cadena)"},
        {"vi", "Giá trị cần tìm (chuỗi)"},
        {"pt", "Valor a buscar (string)"},
        {"fr", "Valeur à rechercher (chaîne)"},
        {"de", "Zu suchender Wert (String)"},
        {"th", "ค่าที่จะค้นหา (สตริง)"},
        {"ar", "القيمة للبحث (نص)"},
    }},
    {"param_type", {
        {"en", "Data type: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"zh", "数据类型: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"ja", "データ型: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"ko", "데이터 타입: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"ru", "Тип данных: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"es", "Tipo de datos: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"vi", "Kiểu dữ liệu: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"pt", "Tipo de dados: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"fr", "Type de données: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"de", "Datentyp: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"th", "ประเภทข้อมูล: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
        {"ar", "نوع البيانات: I8, I16, I32, I64, U8, U16, U32, U64, F32, F64"},
    }},
    {"param_from", {
        {"en", "Start address (optional)"},
        {"zh", "起始地址 (可选, 默认使用设置)"},
        {"ja", "開始アドレス (オプション)"},
        {"ko", "시작 주소 (선택사항)"},
        {"ru", "Начальный адрес (необязательно)"},
        {"es", "Dirección de inicio (opcional)"},
        {"vi", "Địa chỉ bắt đầu (tùy chọn)"},
        {"pt", "Endereço inicial (opcional)"},
        {"fr", "Adresse de début (optionnel)"},
        {"de", "Startadresse (optional)"},
        {"th", "ที่อยู่เริ่มต้น (ไม่บังคับ)"},
        {"ar", "عنوان البداية (اختياري)"},
    }},
    {"param_to", {
        {"en", "End address (optional)"},
        {"zh", "结束地址 (可选, 默认使用设置)"},
        {"ja", "終了アドレス (オプション)"},
        {"ko", "끝 주소 (선택사항)"},
        {"ru", "Конечный адрес (необязательно)"},
        {"es", "Dirección de fin (opcional)"},
        {"vi", "Địa chỉ kết thúc (tùy chọn)"},
        {"pt", "Endereço final (opcional)"},
        {"fr", "Adresse de fin (optionnel)"},
        {"de", "Endadresse (optional)"},
        {"th", "ที่อยู่สิ้นสุด (ไม่บังคับ)"},
        {"ar", "عنوان النهاية (اختياري)"},
    }},
    {"param_filter_value", {
        {"en", "Filter value"},
        {"zh", "筛选数值"},
        {"ja", "フィルター値"},
        {"ko", "필터 값"},
        {"ru", "Значение фильтра"},
        {"es", "Valor de filtro"},
        {"vi", "Giá trị lọc"},
        {"pt", "Valor de filtro"},
        {"fr", "Valeur de filtre"},
        {"de", "Filterwert"},
        {"th", "ค่าตัวกรอง"},
        {"ar", "قيمة التصفية"},
    }},
    {"param_mode", {
        {"en", "Compare mode: eq(equal), gt(greater), lt(less), chg(changed), inc(increased by), dec(decreased by)"},
        {"zh", "比对模式: eq(等于), gt(大于), lt(小于), chg(变化), inc(增加了), dec(减少了)"},
        {"ja", "比較モード: eq(等しい), gt(より大きい), lt(より小さい), chg(変化), inc(増加), dec(減少)"},
        {"ko", "비교 모드: eq(같음), gt(큼), lt(작음), chg(변경됨), inc(증가), dec(감소)"},
        {"ru", "Режим сравнения: eq(равно), gt(больше), lt(меньше), chg(изменилось), inc(увеличилось на), dec(уменьшилось на)"},
        {"es", "Modo de comparación: eq(igual), gt(mayor), lt(menor), chg(cambió), inc(aumentó en), dec(disminuyó en)"},
        {"vi", "Chế độ so sánh: eq(bằng), gt(lớn hơn), lt(nhỏ hơn), chg(thay đổi), inc(tăng), dec(giảm)"},
        {"pt", "Modo de comparação: eq(igual), gt(maior), lt(menor), chg(mudou), inc(aumentou em), dec(diminuiu em)"},
        {"fr", "Mode de comparaison: eq(égal), gt(supérieur), lt(inférieur), chg(changé), inc(augmenté de), dec(diminué de)"},
        {"de", "Vergleichsmodus: eq(gleich), gt(größer), lt(kleiner), chg(geändert), inc(erhöht um), dec(verringert um)"},
        {"th", "โหมดเปรียบเทียบ: eq(เท่ากับ), gt(มากกว่า), lt(น้อยกว่า), chg(เปลี่ยนแปลง), inc(เพิ่มขึ้น), dec(ลดลง)"},
        {"ar", "وضع المقارنة: eq(يساوي), gt(أكبر), lt(أصغر), chg(تغير), inc(زاد بـ), dec(نقص بـ)"},
    }},
    {"param_values_expr", {
        {"en", "Value expression, separated by semicolons. Format: value [type][::range]"},
        {"zh", "数值表达式，用分号分隔。格式: 数值 [类型][::范围]"},
        {"ja", "値式、セミコロンで区切り。形式: 値 [型][::範囲]"},
        {"ko", "값 표현식, 세미콜론으로 구분. 형식: 값 [타입][::범위]"},
        {"ru", "Выражение значений, разделённое точкой с запятой. Формат: значение [тип][::диапазон]"},
        {"es", "Expresión de valores, separada por punto y coma. Formato: valor [tipo][::rango]"},
        {"vi", "Biểu thức giá trị, phân cách bằng dấu chấm phẩy. Định dạng: giá trị [kiểu][::phạm vi]"},
        {"pt", "Expressão de valores, separada por ponto e vírgula. Formato: valor [tipo][::intervalo]"},
        {"fr", "Expression de valeurs, séparée par des points-virgules. Format: valeur [type][::plage]"},
        {"de", "Wertausdruck, durch Semikolon getrennt. Format: Wert [Typ][::Bereich]"},
        {"th", "นิพจน์ค่า คั่นด้วยเซมิโคลอน รูปแบบ: ค่า [ประเภท][::ช่วง]"},
        {"ar", "تعبير القيم، مفصول بفاصلة منقوطة. التنسيق: قيمة [نوع][::نطاق]"},
    }},
    {"param_default_type", {
        {"en", "Default data type (used when type not specified)"},
        {"zh", "默认数据类型 (未指定类型时使用)"},
        {"ja", "デフォルトデータ型 (型が指定されていない場合に使用)"},
        {"ko", "기본 데이터 타입 (타입이 지정되지 않은 경우 사용)"},
        {"ru", "Тип данных по умолчанию (используется, когда тип не указан)"},
        {"es", "Tipo de datos predeterminado (usado cuando no se especifica tipo)"},
        {"vi", "Kiểu dữ liệu mặc định (sử dụng khi không chỉ định kiểu)"},
        {"pt", "Tipo de dados padrão (usado quando tipo não especificado)"},
        {"fr", "Type de données par défaut (utilisé quand le type n'est pas spécifié)"},
        {"de", "Standard-Datentyp (verwendet wenn Typ nicht angegeben)"},
        {"th", "ประเภทข้อมูลเริ่มต้น (ใช้เมื่อไม่ระบุประเภท)"},
        {"ar", "نوع البيانات الافتراضي (يستخدم عند عدم تحديد النوع)"},
    }},
    {"param_range", {
        {"en", "Search range in bytes (default: 50)"},
        {"zh", "搜索范围 (字节数, 默认50)"},
        {"ja", "検索範囲（バイト単位、デフォルト: 50）"},
        {"ko", "검색 범위 (바이트, 기본값: 50)"},
        {"ru", "Диапазон поиска в байтах (по умолчанию: 50)"},
        {"es", "Rango de búsqueda en bytes (predeterminado: 50)"},
        {"vi", "Phạm vi tìm kiếm tính bằng byte (mặc định: 50)"},
        {"pt", "Intervalo de busca em bytes (padrão: 50)"},
        {"fr", "Plage de recherche en octets (par défaut: 50)"},
        {"de", "Suchbereich in Bytes (Standard: 50)"},
        {"th", "ช่วงการค้นหาเป็นไบต์ (ค่าเริ่มต้น: 50)"},
        {"ar", "نطاق البحث بالبايت (افتراضي: 50)"},
    }},
    {"param_signature", {
        {"en", "Hex pattern, ?? for any byte"},
        {"zh", "十六进制特征码，?? 表示任意字节"},
        {"ja", "16進パターン、??は任意のバイト"},
        {"ko", "16진수 패턴, ??는 임의의 바이트"},
        {"ru", "Hex-паттерн, ?? для любого байта"},
        {"es", "Patrón hex, ?? para cualquier byte"},
        {"vi", "Mẫu hex, ?? cho bất kỳ byte nào"},
        {"pt", "Padrão hex, ?? para qualquer byte"},
        {"fr", "Motif hex, ?? pour n'importe quel octet"},
        {"de", "Hex-Muster, ?? für beliebiges Byte"},
        {"th", "รูปแบบ hex, ?? สำหรับไบต์ใดๆ"},
        {"ar", "نمط hex، ?? لأي بايت"},
    }},
    {"param_lock_value", {
        {"en", "Value to lock"},
        {"zh", "锁定的数值"},
        {"ja", "ロックする値"},
        {"ko", "잠글 값"},
        {"ru", "Значение для блокировки"},
        {"es", "Valor a bloquear"},
        {"vi", "Giá trị cần khóa"},
        {"pt", "Valor a bloquear"},
        {"fr", "Valeur à verrouiller"},
        {"de", "Zu sperrender Wert"},
        {"th", "ค่าที่จะล็อก"},
        {"ar", "القيمة للقفل"},
    }},
    {"param_index_filter", {
        {"en", "lock uses index, lockAll uses filter"},
        {"zh", "lock用索引, lockAll用过滤条件"},
        {"ja", "lockはインデックス、lockAllはフィルターを使用"},
        {"ko", "lock은 인덱스, lockAll은 필터 사용"},
        {"ru", "lock использует индекс, lockAll использует фильтр"},
        {"es", "lock usa índice, lockAll usa filtro"},
        {"vi", "lock dùng chỉ mục, lockAll dùng bộ lọc"},
        {"pt", "lock usa índice, lockAll usa filtro"},
        {"fr", "lock utilise l'index, lockAll utilise le filtre"},
        {"de", "lock verwendet Index, lockAll verwendet Filter"},
        {"th", "lock ใช้ดัชนี, lockAll ใช้ตัวกรอง"},
        {"ar", "lock يستخدم الفهرس، lockAll يستخدم الفلتر"},
    }},

    {"comment_basic_search", {
        {"en", "// Basic search"},
        {"zh", "// 基础搜索"},
        {"ja", "// 基本検索"},
        {"ko", "// 기본 검색"},
        {"ru", "// Базовый поиск"},
        {"es", "// Búsqueda básica"},
        {"vi", "// Tìm kiếm cơ bản"},
        {"pt", "// Busca básica"},
        {"fr", "// Recherche basique"},
        {"de", "// Einfache Suche"},
        {"th", "// ค้นหาพื้นฐาน"},
        {"ar", "// بحث أساسي"},
    }},
    {"comment_search_range", {
        {"en", "// Search with range"},
        {"zh", "// 指定范围搜索"},
        {"ja", "// 範囲指定検索"},
        {"ko", "// 범위 지정 검색"},
        {"ru", "// Поиск с диапазоном"},
        {"es", "// Búsqueda con rango"},
        {"vi", "// Tìm kiếm với phạm vi"},
        {"pt", "// Busca com intervalo"},
        {"fr", "// Recherche avec plage"},
        {"de", "// Suche mit Bereich"},
        {"th", "// ค้นหาพร้อมช่วง"},
        {"ar", "// بحث مع نطاق"},
    }},
    {"comment_exact_match", {
        {"en", "// Exact match"},
        {"zh", "// 精确匹配"},
        {"ja", "// 完全一致"},
        {"ko", "// 정확히 일치"},
        {"ru", "// Точное совпадение"},
        {"es", "// Coincidencia exacta"},
        {"vi", "// Khớp chính xác"},
        {"pt", "// Correspondência exata"},
        {"fr", "// Correspondance exacte"},
        {"de", "// Exakte Übereinstimmung"},
        {"th", "// ตรงกันทุกประการ"},
        {"ar", "// تطابق دقيق"},
    }},
    {"comment_value_increased", {
        {"en", "// Value increased by"},
        {"zh", "// 数值增加了"},
        {"ja", "// 値が増加"},
        {"ko", "// 값이 증가함"},
        {"ru", "// Значение увеличилось на"},
        {"es", "// Valor aumentó en"},
        {"vi", "// Giá trị tăng"},
        {"pt", "// Valor aumentou em"},
        {"fr", "// Valeur augmentée de"},
        {"de", "// Wert erhöht um"},
        {"th", "// ค่าเพิ่มขึ้น"},
        {"ar", "// القيمة زادت بـ"},
    }},
    {"comment_value_decreased", {
        {"en", "// Value decreased by"},
        {"zh", "// 数值减少了"},
        {"ja", "// 値が減少"},
        {"ko", "// 값이 감소함"},
        {"ru", "// Значение уменьшилось на"},
        {"es", "// Valor disminuyó en"},
        {"vi", "// Giá trị giảm"},
        {"pt", "// Valor diminuiu em"},
        {"fr", "// Valeur diminuée de"},
        {"de", "// Wert verringert um"},
        {"th", "// ค่าลดลง"},
        {"ar", "// القيمة نقصت بـ"},
    }},
    {"comment_value_changed", {
        {"en", "// Value changed"},
        {"zh", "// 数值变化了"},
        {"ja", "// 値が変化"},
        {"ko", "// 값이 변경됨"},
        {"ru", "// Значение изменилось"},
        {"es", "// Valor cambió"},
        {"vi", "// Giá trị thay đổi"},
        {"pt", "// Valor mudou"},
        {"fr", "// Valeur changée"},
        {"de", "// Wert geändert"},
        {"th", "// ค่าเปลี่ยนแปลง"},
        {"ar", "// القيمة تغيرت"},
    }},
    {"comment_greater_than", {
        {"en", "// Greater than"},
        {"zh", "// 大于某值"},
        {"ja", "// より大きい"},
        {"ko", "// 보다 큼"},
        {"ru", "// Больше чем"},
        {"es", "// Mayor que"},
        {"vi", "// Lớn hơn"},
        {"pt", "// Maior que"},
        {"fr", "// Supérieur à"},
        {"de", "// Größer als"},
        {"th", "// มากกว่า"},
        {"ar", "// أكبر من"},
    }},
    {"comment_less_than", {
        {"en", "// Less than"},
        {"zh", "// 小于某值"},
        {"ja", "// より小さい"},
        {"ko", "// 보다 작음"},
        {"ru", "// Меньше чем"},
        {"es", "// Menor que"},
        {"vi", "// Nhỏ hơn"},
        {"pt", "// Menor que"},
        {"fr", "// Inférieur à"},
        {"de", "// Kleiner als"},
        {"th", "// น้อยกว่า"},
        {"ar", "// أصغر من"},
    }},

    {"card_editall_adv_title", {
        {"en", "Advanced Batch Modify (editAll Filter Syntax)"},
        {"zh", "高级批量修改 (editAll 过滤语法)"},
        {"ja", "高度な一括変更 (editAll フィルター構文)"},
        {"ko", "고급 일괄 수정 (editAll 필터 구문)"},
        {"ru", "Расширенное пакетное изменение (синтаксис фильтра editAll)"},
        {"es", "Modificación Avanzada por Lotes (Sintaxis de Filtro editAll)"},
        {"vi", "Sửa Đổi Hàng Loạt Nâng Cao (Cú Pháp Lọc editAll)"},
        {"pt", "Modificação em Lote Avançada (Sintaxe de Filtro editAll)"},
        {"fr", "Modification par Lots Avancée (Syntaxe de Filtre editAll)"},
        {"de", "Erweiterte Stapelmodifikation (editAll Filter-Syntax)"},
        {"th", "แก้ไขเป็นชุดขั้นสูง (ไวยากรณ์ตัวกรอง editAll)"},
        {"ar", "تعديل دفعي متقدم (صيغة فلتر editAll)"},
    }},
    {"desc_editall_adv", {
        {"en", "The third parameter of vm.editAll supports complex filter combinations for precise control over which results to modify."},
        {"zh", "vm.editAll 第三个参数支持复杂的过滤条件组合，可精确控制修改哪些结果。"},
        {"ja", "vm.editAll の第3パラメータは、どの結果を変更するかを正確に制御するための複雑なフィルター組み合わせをサポートします。"},
        {"ko", "vm.editAll의 세 번째 매개변수는 수정할 결과를 정밀하게 제어하기 위한 복잡한 필터 조합을 지원합니다."},
        {"ru", "Третий параметр vm.editAll поддерживает сложные комбинации фильтров для точного контроля над изменяемыми результатами."},
        {"es", "El tercer parámetro de vm.editAll soporta combinaciones de filtros complejas para control preciso sobre qué resultados modificar."},
        {"vi", "Tham số thứ ba của vm.editAll hỗ trợ kết hợp bộ lọc phức tạp để kiểm soát chính xác kết quả nào cần sửa đổi."},
        {"pt", "O terceiro parâmetro de vm.editAll suporta combinações de filtros complexas para controle preciso sobre quais resultados modificar."},
        {"fr", "Le troisième paramètre de vm.editAll prend en charge des combinaisons de filtres complexes pour un contrôle précis des résultats à modifier."},
        {"de", "Der dritte Parameter von vm.editAll unterstützt komplexe Filterkombinationen für präzise Kontrolle über zu ändernde Ergebnisse."},
        {"th", "พารามิเตอร์ที่สามของ vm.editAll รองรับการรวมตัวกรองที่ซับซ้อนเพื่อควบคุมผลลัพธ์ที่จะแก้ไขอย่างแม่นยำ"},
        {"ar", "المعامل الثالث لـ vm.editAll يدعم مجموعات فلاتر معقدة للتحكم الدقيق في النتائج المراد تعديلها."},
    }},
    {"th_syntax", {
        {"en", "Syntax"},
        {"zh", "语法"},
        {"ja", "構文"},
        {"ko", "구문"},
        {"ru", "Синтаксис"},
        {"es", "Sintaxis"},
        {"vi", "Cú pháp"},
        {"pt", "Sintaxe"},
        {"fr", "Syntaxe"},
        {"de", "Syntax"},
        {"th", "ไวยากรณ์"},
        {"ar", "الصيغة"},
    }},
    {"th_example", {
        {"en", "Example"},
        {"zh", "示例"},
        {"ja", "例"},
        {"ko", "예시"},
        {"ru", "Пример"},
        {"es", "Ejemplo"},
        {"vi", "Ví dụ"},
        {"pt", "Exemplo"},
        {"fr", "Exemple"},
        {"de", "Beispiel"},
        {"th", "ตัวอย่าง"},
        {"ar", "مثال"},
    }},
    {"filter_single_index", {
        {"en", "Modify single index (1-based)"},
        {"zh", "修改单个索引 (从1开始)"},
        {"ja", "単一インデックスを変更 (1から開始)"},
        {"ko", "단일 인덱스 수정 (1부터 시작)"},
        {"ru", "Изменить один индекс (начиная с 1)"},
        {"es", "Modificar índice único (basado en 1)"},
        {"vi", "Sửa đổi chỉ mục đơn (bắt đầu từ 1)"},
        {"pt", "Modificar índice único (baseado em 1)"},
        {"fr", "Modifier un seul index (basé sur 1)"},
        {"de", "Einzelnen Index ändern (1-basiert)"},
        {"th", "แก้ไขดัชนีเดียว (เริ่มจาก 1)"},
        {"ar", "تعديل فهرس واحد (يبدأ من 1)"},
    }},
    {"filter_multi_index", {
        {"en", "Modify multiple indices"},
        {"zh", "修改多个指定索引"},
        {"ja", "複数のインデックスを変更"},
        {"ko", "여러 인덱스 수정"},
        {"ru", "Изменить несколько индексов"},
        {"es", "Modificar múltiples índices"},
        {"vi", "Sửa đổi nhiều chỉ mục"},
        {"pt", "Modificar múltiplos índices"},
        {"fr", "Modifier plusieurs index"},
        {"de", "Mehrere Indizes ändern"},
        {"th", "แก้ไขหลายดัชนี"},
        {"ar", "تعديل فهارس متعددة"},
    }},
    {"filter_range", {
        {"en", "Modify index range N to M"},
        {"zh", "修改索引范围 N 到 M"},
        {"ja", "インデックス範囲 N から M を変更"},
        {"ko", "인덱스 범위 N에서 M까지 수정"},
        {"ru", "Изменить диапазон индексов от N до M"},
        {"es", "Modificar rango de índices N a M"},
        {"vi", "Sửa đổi phạm vi chỉ mục N đến M"},
        {"pt", "Modificar intervalo de índices N a M"},
        {"fr", "Modifier la plage d'index N à M"},
        {"de", "Indexbereich N bis M ändern"},
        {"th", "แก้ไขช่วงดัชนี N ถึง M"},
        {"ar", "تعديل نطاق الفهرس من N إلى M"},
    }},
    {"filter_addr_suffix", {
        {"en", "Address suffix match (hex)"},
        {"zh", "地址尾数匹配 (十六进制)"},
        {"ja", "アドレス末尾一致 (16進数)"},
        {"ko", "주소 접미사 일치 (16진수)"},
        {"ru", "Совпадение суффикса адреса (hex)"},
        {"es", "Coincidencia de sufijo de dirección (hex)"},
        {"vi", "Khớp hậu tố địa chỉ (hex)"},
        {"pt", "Correspondência de sufixo de endereço (hex)"},
        {"fr", "Correspondance du suffixe d'adresse (hex)"},
        {"de", "Adress-Suffix-Übereinstimmung (hex)"},
        {"th", "จับคู่ส่วนท้ายที่อยู่ (hex)"},
        {"ar", "مطابقة لاحقة العنوان (hex)"},
    }},
    {"filter_value_contains", {
        {"en", "Current value contains string"},
        {"zh", "当前值包含指定字符串"},
        {"ja", "現在の値に文字列が含まれる"},
        {"ko", "현재 값에 문자열 포함"},
        {"ru", "Текущее значение содержит строку"},
        {"es", "Valor actual contiene cadena"},
        {"vi", "Giá trị hiện tại chứa chuỗi"},
        {"pt", "Valor atual contém string"},
        {"fr", "La valeur actuelle contient la chaîne"},
        {"de", "Aktueller Wert enthält Zeichenkette"},
        {"th", "ค่าปัจจุบันมีสตริง"},
        {"ar", "القيمة الحالية تحتوي على نص"},
    }},
    {"filter_offset", {
        {"en", "Write address offset (supports hex)"},
        {"zh", "写入地址偏移 (支持十六进制)"},
        {"ja", "書き込みアドレスオフセット (16進数対応)"},
        {"ko", "쓰기 주소 오프셋 (16진수 지원)"},
        {"ru", "Смещение адреса записи (поддерживает hex)"},
        {"es", "Desplazamiento de dirección de escritura (soporta hex)"},
        {"vi", "Độ lệch địa chỉ ghi (hỗ trợ hex)"},
        {"pt", "Deslocamento de endereço de escrita (suporta hex)"},
        {"fr", "Décalage d'adresse d'écriture (supporte hex)"},
        {"de", "Schreibadress-Offset (unterstützt hex)"},
        {"th", "ออฟเซ็ตที่อยู่เขียน (รองรับ hex)"},
        {"ar", "إزاحة عنوان الكتابة (يدعم hex)"},
    }},
    {"filter_ex_single", {
        {"en", "'3' modify 3rd"},
        {"zh", "'3' 修改第3个"},
        {"ja", "'3' 3番目を変更"},
        {"ko", "'3' 3번째 수정"},
        {"ru", "'3' изменить 3-й"},
        {"es", "'3' modificar 3ro"},
        {"vi", "'3' sửa thứ 3"},
        {"pt", "'3' modificar 3º"},
        {"fr", "'3' modifier le 3ème"},
        {"de", "'3' 3. ändern"},
        {"th", "'3' แก้ไขที่ 3"},
        {"ar", "'3' تعديل الثالث"},
    }},
    {"filter_ex_multi", {
        {"en", "'1,3,5' or '1.3.5'"},
        {"zh", "'1,3,5' 或 '1.3.5'"},
        {"ja", "'1,3,5' または '1.3.5'"},
        {"ko", "'1,3,5' 또는 '1.3.5'"},
        {"ru", "'1,3,5' или '1.3.5'"},
        {"es", "'1,3,5' o '1.3.5'"},
        {"vi", "'1,3,5' hoặc '1.3.5'"},
        {"pt", "'1,3,5' ou '1.3.5'"},
        {"fr", "'1,3,5' ou '1.3.5'"},
        {"de", "'1,3,5' oder '1.3.5'"},
        {"th", "'1,3,5' หรือ '1.3.5'"},
        {"ar", "'1,3,5' أو '1.3.5'"},
    }},
    {"filter_ex_range", {
        {"en", "'1=10' modify 1st to 10th"},
        {"zh", "'1=10' 修改第1到10个"},
        {"ja", "'1=10' 1番目から10番目を変更"},
        {"ko", "'1=10' 1번째부터 10번째까지 수정"},
        {"ru", "'1=10' изменить с 1-го по 10-й"},
        {"es", "'1=10' modificar del 1ro al 10mo"},
        {"vi", "'1=10' sửa từ 1 đến 10"},
        {"pt", "'1=10' modificar do 1º ao 10º"},
        {"fr", "'1=10' modifier du 1er au 10ème"},
        {"de", "'1=10' 1. bis 10. ändern"},
        {"th", "'1=10' แก้ไขที่ 1 ถึง 10"},
        {"ar", "'1=10' تعديل من 1 إلى 10"},
    }},
    {"filter_ex_suffix", {
        {"en", "'@ABC' addr ends with ABC"},
        {"zh", "'@ABC' 地址以ABC结尾"},
        {"ja", "'@ABC' アドレスがABCで終わる"},
        {"ko", "'@ABC' 주소가 ABC로 끝남"},
        {"ru", "'@ABC' адрес заканчивается на ABC"},
        {"es", "'@ABC' dirección termina en ABC"},
        {"vi", "'@ABC' địa chỉ kết thúc bằng ABC"},
        {"pt", "'@ABC' endereço termina com ABC"},
        {"fr", "'@ABC' adresse se termine par ABC"},
        {"de", "'@ABC' Adresse endet mit ABC"},
        {"th", "'@ABC' ที่อยู่ลงท้ายด้วย ABC"},
        {"ar", "'@ABC' العنوان ينتهي بـ ABC"},
    }},
    {"filter_ex_contains", {
        {"en", "'||100' value contains 100"},
        {"zh", "'||100' 值包含100"},
        {"ja", "'||100' 値に100が含まれる"},
        {"ko", "'||100' 값에 100 포함"},
        {"ru", "'||100' значение содержит 100"},
        {"es", "'||100' valor contiene 100"},
        {"vi", "'||100' giá trị chứa 100"},
        {"pt", "'||100' valor contém 100"},
        {"fr", "'||100' valeur contient 100"},
        {"de", "'||100' Wert enthält 100"},
        {"th", "'||100' ค่ามี 100"},
        {"ar", "'||100' القيمة تحتوي 100"},
    }},
    {"filter_ex_offset", {
        {"en", "'//+4' addr+4, '//-0x10' addr-16"},
        {"zh", "'//+4' 地址+4, '//-0x10' 地址-16"},
        {"ja", "'//+4' アドレス+4, '//-0x10' アドレス-16"},
        {"ko", "'//+4' 주소+4, '//-0x10' 주소-16"},
        {"ru", "'//+4' адрес+4, '//-0x10' адрес-16"},
        {"es", "'//+4' dir+4, '//-0x10' dir-16"},
        {"vi", "'//+4' địa chỉ+4, '//-0x10' địa chỉ-16"},
        {"pt", "'//+4' end+4, '//-0x10' end-16"},
        {"fr", "'//+4' adr+4, '//-0x10' adr-16"},
        {"de", "'//+4' Adr+4, '//-0x10' Adr-16"},
        {"th", "'//+4' ที่อยู่+4, '//-0x10' ที่อยู่-16"},
        {"ar", "'//+4' عنوان+4, '//-0x10' عنوان-16"},
    }},

    {"section_12", {
        {"en", "12. Pointer Chain"},
        {"zh", "12. 指针链 (Pointer Chain)"},
        {"ja", "12. ポインタチェーン"},
        {"ko", "12. 포인터 체인"},
        {"ru", "12. Цепочка указателей"},
        {"es", "12. Cadena de Punteros"},
        {"vi", "12. Chuỗi Con Trỏ"},
        {"pt", "12. Cadeia de Ponteiros"},
        {"fr", "12. Chaîne de Pointeurs"},
        {"de", "12. Zeigerkette"},
        {"th", "12. ห่วงโซ่พอยน์เตอร์"},
        {"ar", "12. سلسلة المؤشرات"},
    }},
    {"desc_pointer", {
        {"en", "Resolve multi-level pointer chains to read/write values at dynamic addresses. Supports module-based and virtual base addresses."},
        {"zh", "解析多级指针链，在动态地址上读写数值。支持基于模块和虚拟基址。"},
        {"ja", "多段ポインタチェーンを解決して動的アドレスの値を読み書き。モジュールベースと仮想ベースアドレスをサポート。"},
        {"ko", "다단계 포인터 체인을 해석하여 동적 주소에서 값을 읽고 씁니다. 모듈 기반 및 가상 기본 주소를 지원합니다."},
        {"ru", "Разрешение многоуровневых цепочек указателей для чтения/записи значений по динамическим адресам."},
        {"es", "Resolver cadenas de punteros multinivel para leer/escribir valores en direcciones dinámicas."},
        {"vi", "Giải quyết chuỗi con trỏ nhiều cấp để đọc/ghi giá trị tại địa chỉ động."},
        {"pt", "Resolver cadeias de ponteiros multinível para ler/escrever valores em endereços dinâmicos."},
        {"fr", "Résoudre les chaînes de pointeurs multi-niveaux pour lire/écrire des valeurs à des adresses dynamiques."},
        {"de", "Mehrstufige Zeigerketten auflösen um Werte an dynamischen Adressen zu lesen/schreiben."},
        {"th", "แก้ไขห่วงโซ่พอยน์เตอร์หลายระดับเพื่ออ่าน/เขียนค่าที่ที่อยู่แบบไดนามิก"},
        {"ar", "حل سلاسل المؤشرات متعددة المستويات لقراءة/كتابة القيم في العناوين الديناميكية."},
    }},
    {"card_pointer_title", {
        {"en", "Pointer Read/Write/Lock"},
        {"zh", "指针读写与锁定"},
        {"ja", "ポインタ読み書きとロック"},
        {"ko", "포인터 읽기/쓰기/잠금"},
        {"ru", "Чтение/запись/блокировка указателей"},
        {"es", "Lectura/Escritura/Bloqueo de Punteros"},
        {"vi", "Đọc/Ghi/Khóa Con Trỏ"},
        {"pt", "Leitura/Escrita/Bloqueio de Ponteiros"},
        {"fr", "Lecture/Écriture/Verrouillage de Pointeurs"},
        {"de", "Zeiger Lesen/Schreiben/Sperren"},
        {"th", "อ่าน/เขียน/ล็อกพอยน์เตอร์"},
        {"ar", "قراءة/كتابة/قفل المؤشرات"},
    }},

    {"rva_jb_warning", {
        {"en", "<b>This feature is only available on jailbroken devices.</b> "},
        {"zh", "<b>此功能仅在越狱环境下可用。</b>"},
        {"ja", "<b>この機能は脱獄デバイスでのみ使用可能です。</b>"},
        {"ko", "<b>이 기능은 탈옥된 기기에서만 사용할 수 있습니다.</b>"},
        {"ru", "<b>Эта функция доступна только на взломанных устройствах.</b> "},
        {"es", "<b>Esta funcion solo esta disponible en dispositivos con jailbreak.</b> "},
        {"vi", "<b>Tinh nang nay chi kha dung tren thiet bi jailbreak.</b> "},
        {"pt", "<b>Este recurso esta disponivel apenas em dispositivos com jailbreak.</b> "},
        {"fr", "<b>Cette fonctionnalite est disponible uniquement sur les appareils jailbreakes.</b> "},
        {"de", "<b>Diese Funktion ist nur auf Jailbreak-Geraeten verfuegbar.</b> "},
        {"th", "<b>ฟีเจอร์นี้ใช้ได้เฉพาะอุปกรณ์ที่เจลเบรคแล้วเท่านั้น</b> "},
        {"ar", "<b>هذه الميزة متاحة فقط على الأجهزة المكسورة.</b> "},
    }},
    {"rva_jb_tag", {
        {"en", "Jailbreak Only"},
        {"zh", "仅限越狱"},
        {"ja", "脱獄のみ"},
        {"ko", "탈옥 전용"},
        {"ru", "Только джейлбрейк"},
        {"es", "Solo Jailbreak"},
        {"vi", "Chỉ Jailbreak"},
        {"pt", "Apenas Jailbreak"},
        {"fr", "Jailbreak uniquement"},
        {"de", "Nur Jailbreak"},
        {"th", "เฉพาะ Jailbreak"},
        {"ar", "جيلبريك فقط"},
    }},
    {"section_13", {
        {"en", "13. RVA Patch"},
        {"zh", "13. RVA 补丁"},
        {"ja", "13. RVAパッチ"},
        {"ko", "13. RVA 패치"},
        {"ru", "13. RVA Патч"},
        {"es", "13. Parche RVA"},
        {"vi", "13. Vá RVA"},
        {"pt", "13. Patch RVA"},
        {"fr", "13. Patch RVA"},
        {"de", "13. RVA-Patch"},
        {"th", "13. แพทช์ RVA"},
        {"ar", "13. تصحيح RVA"},
    }},
    {"desc_rva", {
        {"en", "Patch executable memory at module+offset using hex bytes. Automatically handles memory protection (RW→RX). Supports read, write, and restore."},
        {"zh", "在模块+偏移处用十六进制字节修补可执行内存。自动处理内存保护 (RW→RX)。支持读取、写入和恢复。"},
        {"ja", "モジュール+オフセットでhexバイトを使用して実行可能メモリをパッチ。メモリ保護を自動処理 (RW→RX)。読み取り、書き込み、復元をサポート。"},
        {"ko", "모듈+오프셋에서 hex 바이트로 실행 가능한 메모리를 패치합니다. 메모리 보호를 자동 처리합니다 (RW→RX)."},
        {"ru", "Патч исполняемой памяти по модулю+смещению с помощью hex-байтов. Автоматическая обработка защиты памяти (RW→RX)."},
        {"es", "Parchear memoria ejecutable en módulo+offset usando bytes hex. Maneja automáticamente la protección de memoria (RW→RX)."},
        {"vi", "Vá bộ nhớ thực thi tại module+offset bằng byte hex. Tự động xử lý bảo vệ bộ nhớ (RW→RX)."},
        {"pt", "Patch de memória executável em módulo+offset usando bytes hex. Trata automaticamente a proteção de memória (RW→RX)."},
        {"fr", "Patcher la mémoire exécutable à module+offset avec des octets hex. Gère automatiquement la protection mémoire (RW→RX)."},
        {"de", "Ausführbaren Speicher bei Modul+Offset mit Hex-Bytes patchen. Speicherschutz wird automatisch behandelt (RW→RX)."},
        {"th", "แพทช์หน่วยความจำที่สามารถเรียกใช้งานได้ที่ module+offset โดยใช้ hex bytes จัดการการป้องกันหน่วยความจำอัตโนมัติ (RW→RX)"},
        {"ar", "تصحيح الذاكرة القابلة للتنفيذ في الوحدة+الإزاحة باستخدام بايتات hex. يتعامل تلقائياً مع حماية الذاكرة (RW→RX)."},
    }},
    {"card_rva_title", {
        {"en", "RVA Read/Patch/Restore"},
        {"zh", "RVA 读取/补丁/恢复"},
        {"ja", "RVA 読み取り/パッチ/復元"},
        {"ko", "RVA 읽기/패치/복원"},
        {"ru", "RVA Чтение/Патч/Восстановление"},
        {"es", "RVA Lectura/Parche/Restauración"},
        {"vi", "RVA Đọc/Vá/Khôi Phục"},
        {"pt", "RVA Leitura/Patch/Restauração"},
        {"fr", "RVA Lecture/Patch/Restauration"},
        {"de", "RVA Lesen/Patchen/Wiederherstellen"},
        {"th", "RVA อ่าน/แพทช์/กู้คืน"},
        {"ar", "RVA قراءة/تصحيح/استعادة"},
    }},

    {"param_pointer_module", {
        {"en", "Module name (e.g. 'UnityFramework')"},
        {"zh", "模块名称 (如 'UnityFramework')"},
        {"ja", "モジュール名 (例: 'UnityFramework')"},
        {"ko", "모듈 이름 (예: 'UnityFramework')"},
        {"ru", "Имя модуля (напр. 'UnityFramework')"},
        {"es", "Nombre del módulo (ej. 'UnityFramework')"},
        {"vi", "Tên module (vd: 'UnityFramework')"},
        {"pt", "Nome do módulo (ex: 'UnityFramework')"},
        {"fr", "Nom du module (ex: 'UnityFramework')"},
        {"de", "Modulname (z.B. 'UnityFramework')"},
        {"th", "ชื่อโมดูล (เช่น 'UnityFramework')"},
        {"ar", "اسم الوحدة (مثل 'UnityFramework')"},
    }},
    {"param_pointer_base", {
        {"en", "Base offset from module start (hex string)"},
        {"zh", "模块起始偏移 (十六进制字符串)"},
        {"ja", "モジュール開始からのベースオフセット (16進文字列)"},
        {"ko", "모듈 시작부터의 기본 오프셋 (16진수 문자열)"},
        {"ru", "Базовое смещение от начала модуля (hex строка)"},
        {"es", "Offset base desde inicio del módulo (cadena hex)"},
        {"vi", "Offset cơ sở từ đầu module (chuỗi hex)"},
        {"pt", "Offset base do início do módulo (string hex)"},
        {"fr", "Offset de base depuis le début du module (chaîne hex)"},
        {"de", "Basis-Offset vom Modulstart (Hex-String)"},
        {"th", "ออฟเซ็ตฐานจากจุดเริ่มต้นโมดูล (สตริง hex)"},
        {"ar", "إزاحة القاعدة من بداية الوحدة (نص hex)"},
    }},
    {"param_pointer_offsets", {
        {"en", "Array of offsets for each pointer level"},
        {"zh", "每级指针的偏移数组"},
        {"ja", "各ポインタレベルのオフセット配列"},
        {"ko", "각 포인터 레벨의 오프셋 배열"},
        {"ru", "Массив смещений для каждого уровня указателя"},
        {"es", "Array de offsets para cada nivel de puntero"},
        {"vi", "Mảng offset cho mỗi cấp con trỏ"},
        {"pt", "Array de offsets para cada nível de ponteiro"},
        {"fr", "Tableau d'offsets pour chaque niveau de pointeur"},
        {"de", "Array von Offsets für jede Zeigerebene"},
        {"th", "อาร์เรย์ของออฟเซ็ตสำหรับแต่ละระดับพอยน์เตอร์"},
        {"ar", "مصفوفة الإزاحات لكل مستوى مؤشر"},
    }},

    {"param_rva_module", {
        {"en", "Target module name"},
        {"zh", "目标模块名称"},
        {"ja", "対象モジュール名"},
        {"ko", "대상 모듈 이름"},
        {"ru", "Имя целевого модуля"},
        {"es", "Nombre del módulo objetivo"},
        {"vi", "Tên module đích"},
        {"pt", "Nome do módulo alvo"},
        {"fr", "Nom du module cible"},
        {"de", "Zielmodulname"},
        {"th", "ชื่อโมดูลเป้าหมาย"},
        {"ar", "اسم الوحدة المستهدفة"},
    }},
    {"param_rva_offset", {
        {"en", "Offset from module base (hex string)"},
        {"zh", "模块基址偏移 (十六进制字符串)"},
        {"ja", "モジュールベースからのオフセット (16進文字列)"},
        {"ko", "모듈 기본 주소로부터의 오프셋 (16진수 문자열)"},
        {"ru", "Смещение от базы модуля (hex строка)"},
        {"es", "Offset desde base del módulo (cadena hex)"},
        {"vi", "Offset từ địa chỉ cơ sở module (chuỗi hex)"},
        {"pt", "Offset da base do módulo (string hex)"},
        {"fr", "Offset depuis la base du module (chaîne hex)"},
        {"de", "Offset von der Modulbasis (Hex-String)"},
        {"th", "ออฟเซ็ตจากฐานโมดูล (สตริง hex)"},
        {"ar", "إزاحة من قاعدة الوحدة (نص hex)"},
    }},
    {"param_rva_hex", {
        {"en", "Hex bytes to write (e.g. 'E0031F2A')"},
        {"zh", "要写入的十六进制字节 (如 'E0031F2A')"},
        {"ja", "書き込むhexバイト (例: 'E0031F2A')"},
        {"ko", "쓸 hex 바이트 (예: 'E0031F2A')"},
        {"ru", "Hex-байты для записи (напр. 'E0031F2A')"},
        {"es", "Bytes hex a escribir (ej. 'E0031F2A')"},
        {"vi", "Byte hex cần ghi (vd: 'E0031F2A')"},
        {"pt", "Bytes hex para escrever (ex: 'E0031F2A')"},
        {"fr", "Octets hex à écrire (ex: 'E0031F2A')"},
        {"de", "Zu schreibende Hex-Bytes (z.B. 'E0031F2A')"},
        {"th", "ไบต์ hex ที่จะเขียน (เช่น 'E0031F2A')"},
        {"ar", "بايتات hex للكتابة (مثل 'E0031F2A')"},
    }},

    {"section_between", {
        {"en", "7. Range Search (Between)"},
        {"zh", "7. 范围搜索 (Between)"},
        {"ja", "7. 範囲検索 (Between)"},
        {"ko", "7. 범위 검색 (Between)"},
        {"ru", "7. Поиск по диапазону (Between)"},
        {"es", "7. Búsqueda por Rango"},
        {"vi", "7. Tìm Kiếm Khoảng"},
        {"pt", "7. Busca por Intervalo"},
        {"fr", "7. Recherche par Plage"},
        {"de", "7. Bereichssuche"},
        {"th", "7. ค้นหาช่วง"},
        {"ar", "7. البحث بالنطاق"},
    }},
    {"desc_between", {
        {"en", "Search for values within a specified range (min~max). Useful for finding values you know fall within a certain range."},
        {"zh", "搜索指定范围内的数值 (最小值~最大值)。适用于已知数值在某个区间内的场景。"},
        {"ja", "指定範囲内の値を検索 (最小値~最大値)。値が特定の範囲内にあることがわかっている場合に便利。"},
        {"ko", "지정된 범위 내의 값을 검색합니다 (최소~최대). 값이 특정 범위 내에 있다는 것을 알 때 유용합니다."},
        {"ru", "Поиск значений в указанном диапазоне (мин~макс). Полезно, когда известно, что значение находится в определённом диапазоне."},
        {"es", "Buscar valores dentro de un rango especificado (mín~máx). Útil para encontrar valores dentro de un rango conocido."},
        {"vi", "Tìm kiếm giá trị trong phạm vi chỉ định (min~max). Hữu ích khi biết giá trị nằm trong một khoảng nhất định."},
        {"pt", "Buscar valores dentro de um intervalo especificado (mín~máx). Útil para encontrar valores dentro de um intervalo conhecido."},
        {"fr", "Rechercher des valeurs dans une plage spécifiée (min~max). Utile pour trouver des valeurs dans une plage connue."},
        {"de", "Werte innerhalb eines angegebenen Bereichs suchen (min~max). Nützlich wenn bekannt ist, dass Werte in einem bestimmten Bereich liegen."},
        {"th", "ค้นหาค่าภายในช่วงที่กำหนด (ต่ำสุด~สูงสุด) มีประโยชน์เมื่อทราบว่าค่าอยู่ในช่วงที่กำหนด"},
        {"ar", "البحث عن قيم ضمن نطاق محدد (أدنى~أقصى). مفيد عند معرفة أن القيمة تقع ضمن نطاق معين."},
    }},
    {"param_between_min", {
        {"en", "Minimum value (string)"},
        {"zh", "最小值 (字符串)"},
        {"ja", "最小値 (文字列)"},
        {"ko", "최소값 (문자열)"},
        {"ru", "Минимальное значение (строка)"},
        {"es", "Valor mínimo (cadena)"},
        {"vi", "Giá trị tối thiểu (chuỗi)"},
        {"pt", "Valor mínimo (string)"},
        {"fr", "Valeur minimale (chaîne)"},
        {"de", "Minimalwert (String)"},
        {"th", "ค่าต่ำสุด (สตริง)"},
        {"ar", "القيمة الدنيا (نص)"},
    }},
    {"param_between_max", {
        {"en", "Maximum value (string)"},
        {"zh", "最大值 (字符串)"},
        {"ja", "最大値 (文字列)"},
        {"ko", "최대값 (문자열)"},
        {"ru", "Максимальное значение (строка)"},
        {"es", "Valor máximo (cadena)"},
        {"vi", "Giá trị tối đa (chuỗi)"},
        {"pt", "Valor máximo (string)"},
        {"fr", "Valeur maximale (chaîne)"},
        {"de", "Maximalwert (String)"},
        {"th", "ค่าสูงสุด (สตริง)"},
        {"ar", "القيمة القصوى (نص)"},
    }},

    {"comment_lock_offset", {
        {"en", "// Lock with address offset (use 0x prefix for hex, e.g. //+0x8)"},
        {"zh", "// 带地址偏移锁定 (十六进制加0x前缀, 如 //+0x8)"},
        {"ja", "// アドレスオフセット付きロック (16進数は0x接頭辞, 例: //+0x8)"},
        {"ko", "// 주소 오프셋으로 잠금 (16진수는 0x 접두사, 예: //+0x8)"},
        {"ru", "// Блокировка со смещением (hex с префиксом 0x, напр. //+0x8)"},
        {"es", "// Bloquear con offset (hex con prefijo 0x, ej. //+0x8)"},
        {"vi", "// Khóa với offset (hex dùng tiền tố 0x, vd: //+0x8)"},
        {"pt", "// Bloquear com offset (hex com prefixo 0x, ex: //+0x8)"},
        {"fr", "// Verrouiller avec offset (hex avec préfixe 0x, ex: //+0x8)"},
        {"de", "// Sperren mit Offset (hex mit 0x-Präfix, z.B. //+0x8)"},
        {"th", "// ล็อกพร้อมออฟเซ็ต (hex ใช้ 0x นำหน้า เช่น //+0x8)"},
        {"ar", "// قفل مع إزاحة (hex مع بادئة 0x، مثل //+0x8)"},
    }},
};

#endif /* VMScriptGuideStrings_h */
